# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-0221e7bd-9426-4fe6-b1e4-71e3faeee717";
      fsType = "ext4";
    };

   # hardware-configuration.nix
boot.initrd.luks.devices = {
  "luks-0221e7bd-9426-4fe6-b1e4-71e3faeee717".device = "/dev/disk/by-uuid/0221e7bd-9426-4fe6-b1e4-71e3faeee717";
  # ADD THIS LINE FOR THE SWAP:
  "luks-0ee6075e-588a-4131-b6e6-9a1cf1bb4f38".device = "/dev/disk/by-uuid/0ee6075e-588a-4131-b6e6-9a1cf1bb4f38";
};


  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F61D-EC27";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-0ee6075e-588a-4131-b6e6-9a1cf1bb4f38"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
